/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;
import javax.swing.*;
/**
 *
 * @author marco
 */
public class WarehousePanel extends javax.swing.JFrame {

    /**
     * Creates new form WarehousePanelEntryArticle
     */
    public WarehousePanel() {
        initComponents();
        closeAllExcept(jPanelMenu);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanelExitArticle = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldForwarderName = new javax.swing.JTextField();
        jTextFieldShopDestinationName = new javax.swing.JTextField();
        jButtonNext = new javax.swing.JButton();
        jComboBoxCategoryArticleExit = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldQuantityExit = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxTypeArticleExit = new javax.swing.JComboBox<>();
        jButtonBackExitArticle = new javax.swing.JButton();
        jLabelCost = new javax.swing.JLabel();
        jComboBoxCost = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanelEntryArticle = new javax.swing.JPanel();
        jLabelInfoCode = new javax.swing.JLabel();
        jComboBoxCategoryArticle = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldQuantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDay = new javax.swing.JTextField();
        jTextFieldMonth = new javax.swing.JTextField();
        jTextFieldYear = new javax.swing.JTextField();
        jButtonAddItems = new javax.swing.JButton();
        jButtonEnd = new javax.swing.JButton();
        jComboBoxTypeArticle = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCost = new javax.swing.JTextField();
        jTextFieldPositionYEntry = new javax.swing.JTextField();
        jButtonBackEntryArticle = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldPositionXEntry = new javax.swing.JTextField();
        jPanelMoveArticle = new javax.swing.JPanel();
        jButtonBackMoveArticle = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldRipianoScaffale = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxCategoryArticleExit1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldQuantityMove = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxTypeArticleExit1 = new javax.swing.JComboBox<>();
        jLabelCost1 = new javax.swing.JLabel();
        jComboBoxCost1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextFieldNumeroScaffale = new javax.swing.JTextField();
        jTextFieldFila = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanelMenu = new javax.swing.JPanel();
        jButtonEntrataArticoli = new javax.swing.JButton();
        jButtonUscitaArticoli = new javax.swing.JButton();
        jButtonSpostamentoArticoli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));

        jPanelExitArticle.setBackground(new java.awt.Color(93, 93, 93));
        jPanelExitArticle.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanelExitArticle.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelExitArticle.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelExitArticle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelExitArticle.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-32594, -32570, -1, -1));

        jLabel6.setBackground(new java.awt.Color(254, 254, 254));
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Uscita articoli n.        in data");
        jPanelExitArticle.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Nome spedizioniere");
        jLabel7.setToolTipText("");
        jPanelExitArticle.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Negozio di destinazione");
        jPanelExitArticle.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jTextFieldForwarderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldForwarderNameActionPerformed(evt);
            }
        });
        jPanelExitArticle.add(jTextFieldForwarderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 290, 25));

        jTextFieldShopDestinationName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldShopDestinationNameActionPerformed(evt);
            }
        });
        jPanelExitArticle.add(jTextFieldShopDestinationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 290, 25));

        jButtonNext.setText("AVANTI");
        jButtonNext.setMaximumSize(new java.awt.Dimension(80, 40));
        jButtonNext.setMinimumSize(new java.awt.Dimension(80, 40));
        jButtonNext.setPreferredSize(new java.awt.Dimension(80, 40));
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        jPanelExitArticle.add(jButtonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 500, 120, -1));

        jComboBoxCategoryArticleExit.setModel(new DefaultComboBoxModel<>(objects.Sport.values()));
        jComboBoxCategoryArticleExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryArticleExitActionPerformed(evt);
            }
        });
        jPanelExitArticle.add(jComboBoxCategoryArticleExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 120, -1));

        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Categoria articolo");
        jPanelExitArticle.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 150, -1));

        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("Quantità");
        jPanelExitArticle.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jTextFieldQuantityExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantityExitActionPerformed(evt);
            }
        });
        jPanelExitArticle.add(jTextFieldQuantityExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 34, -1));

        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Tipo di articolo");
        jPanelExitArticle.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jComboBoxTypeArticleExit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTypeArticleExit.setSelectedItem(this);
        jComboBoxTypeArticleExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeArticleExitActionPerformed(evt);
            }
        });
        jPanelExitArticle.add(jComboBoxTypeArticleExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 120, -1));

        jButtonBackExitArticle.setText("INDIETRO");
        jButtonBackExitArticle.setPreferredSize(new java.awt.Dimension(80, 40));
        jButtonBackExitArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackExitArticleActionPerformed(evt);
            }
        });
        jPanelExitArticle.add(jButtonBackExitArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 120, -1));

        jLabelCost.setForeground(new java.awt.Color(254, 254, 254));
        jLabelCost.setText("Prezzo");
        jPanelExitArticle.add(jLabelCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jComboBoxCost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelExitArticle.add(jComboBoxCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jLabel13.setForeground(new java.awt.Color(254, 254, 254));
        jLabel13.setText("Posizione");
        jPanelExitArticle.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelExitArticle.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 280, -1));

        jPanelEntryArticle.setBackground(new java.awt.Color(93, 93, 93));
        jPanelEntryArticle.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanelEntryArticle.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelEntryArticle.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelEntryArticle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelInfoCode.setForeground(new java.awt.Color(254, 254, 254));
        jLabelInfoCode.setText("Registrazione entrata articoli n. ");
        jPanelEntryArticle.add(jLabelInfoCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 23, 412, -1));

        jComboBoxCategoryArticle.setModel(new DefaultComboBoxModel<>(objects.Sport.values()));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextFieldDay, org.jdesktop.beansbinding.ObjectProperty.create(), jComboBoxCategoryArticle, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBoxCategoryArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryArticleActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jComboBoxCategoryArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 88, 120, -1));

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Categoria articolo");
        jPanelEntryArticle.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, -1));

        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Quantità");
        jPanelEntryArticle.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jTextFieldQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantityActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jTextFieldQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 34, -1));

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Tipo di articolo");
        jPanelEntryArticle.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Data di produzione");
        jPanelEntryArticle.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jTextFieldDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDayActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jTextFieldDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 278, 34, -1));
        jPanelEntryArticle.add(jTextFieldMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 278, 34, -1));
        jPanelEntryArticle.add(jTextFieldYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 278, 82, -1));

        jButtonAddItems.setText("Aggiungi altri articoli");
        jButtonAddItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemsActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jButtonAddItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));

        jButtonEnd.setText("FINE");
        jButtonEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEndActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jButtonEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        jComboBoxTypeArticle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTypeArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeArticleActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jComboBoxTypeArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 120, -1));

        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Prezzo");
        jPanelEntryArticle.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 130, -1));

        jTextFieldCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCostActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jTextFieldCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 30, -1));
        jPanelEntryArticle.add(jTextFieldPositionYEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 30, -1));

        jButtonBackEntryArticle.setText("INDIETRO");
        jButtonBackEntryArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackEntryArticleActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jButtonBackEntryArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel18.setForeground(new java.awt.Color(254, 254, 254));
        jLabel18.setText("Posizione");
        jPanelEntryArticle.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, -1));

        jTextFieldPositionXEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPositionXEntryActionPerformed(evt);
            }
        });
        jPanelEntryArticle.add(jTextFieldPositionXEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 30, -1));

        jPanelMoveArticle.setBackground(new java.awt.Color(93, 93, 93));
        jPanelMoveArticle.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanelMoveArticle.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelMoveArticle.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelMoveArticle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBackMoveArticle.setText("INDIETRO");
        jButtonBackMoveArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackMoveArticleActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jButtonBackMoveArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 120, -1));

        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("NUOVA POSIZIONE");
        jPanelMoveArticle.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, 20));

        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setText("Fila");
        jPanelMoveArticle.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 20));

        jLabel15.setForeground(new java.awt.Color(254, 254, 254));
        jLabel15.setText("SPOSTA ARTICOLI");
        jPanelMoveArticle.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 130, 20));

        jTextFieldRipianoScaffale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRipianoScaffaleActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jTextFieldRipianoScaffale, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 40, -1));

        jLabel16.setForeground(new java.awt.Color(254, 254, 254));
        jLabel16.setText("Numero scaffale");
        jPanelMoveArticle.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 20));

        jLabel17.setForeground(new java.awt.Color(254, 254, 254));
        jLabel17.setText("Ripiano Scaffale");
        jPanelMoveArticle.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, 20));

        jComboBoxCategoryArticleExit1.setModel(new DefaultComboBoxModel<>(objects.Sport.values()));
        jComboBoxCategoryArticleExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryArticleExit1ActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jComboBoxCategoryArticleExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 120, -1));

        jLabel19.setForeground(new java.awt.Color(254, 254, 254));
        jLabel19.setText("Categoria articolo");
        jPanelMoveArticle.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 150, -1));

        jLabel20.setForeground(new java.awt.Color(254, 254, 254));
        jLabel20.setText("Quantità");
        jPanelMoveArticle.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jTextFieldQuantityMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantityMoveActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jTextFieldQuantityMove, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 34, -1));

        jLabel21.setForeground(new java.awt.Color(254, 254, 254));
        jLabel21.setText("Tipo di articolo");
        jPanelMoveArticle.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jComboBoxTypeArticleExit1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COTOLETTA COL TONNO" }));
        jComboBoxTypeArticleExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeArticleExit1ActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jComboBoxTypeArticleExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 120, -1));

        jLabelCost1.setForeground(new java.awt.Color(254, 254, 254));
        jLabelCost1.setText("Prezzo");
        jPanelMoveArticle.add(jLabelCost1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jComboBoxCost1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelMoveArticle.add(jComboBoxCost1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jLabel22.setForeground(new java.awt.Color(254, 254, 254));
        jLabel22.setText("Posizione");
        jPanelMoveArticle.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelMoveArticle.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 280, -1));

        jTextFieldNumeroScaffale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroScaffaleActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jTextFieldNumeroScaffale, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 40, -1));

        jTextFieldFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFilaActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jTextFieldFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 40, -1));

        jButton1.setText("FINE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelMoveArticle.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, -1, -1));

        jPanelMenu.setBackground(new java.awt.Color(93, 93, 93));
        jPanelMenu.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanelMenu.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEntrataArticoli.setText("Entrata Articoli");
        jButtonEntrataArticoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrataArticoliActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonEntrataArticoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 185, 48));

        jButtonUscitaArticoli.setText("Uscita Articoli");
        jButtonUscitaArticoli.setMaximumSize(new java.awt.Dimension(115, 29));
        jButtonUscitaArticoli.setMinimumSize(new java.awt.Dimension(115, 29));
        jButtonUscitaArticoli.setPreferredSize(new java.awt.Dimension(115, 29));
        jButtonUscitaArticoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUscitaArticoliActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonUscitaArticoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 185, 48));

        jButtonSpostamentoArticoli.setText("Sposta Articoli");
        jButtonSpostamentoArticoli.setMaximumSize(new java.awt.Dimension(115, 29));
        jButtonSpostamentoArticoli.setMinimumSize(new java.awt.Dimension(115, 29));
        jButtonSpostamentoArticoli.setPreferredSize(new java.awt.Dimension(115, 29));
        jButtonSpostamentoArticoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpostamentoArticoliActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonSpostamentoArticoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 185, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEntryArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelExitArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMoveArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEntryArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelExitArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMoveArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDayActionPerformed

    private void jComboBoxCategoryArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryArticleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoryArticleActionPerformed

    //rende visibile entrata articoli
    private void jButtonEntrataArticoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrataArticoliActionPerformed
        
        //Rende visibile il pannello registra articoli
        closeAllExcept(jPanelEntryArticle);
    }//GEN-LAST:event_jButtonEntrataArticoliActionPerformed

    private void jButtonUscitaArticoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUscitaArticoliActionPerformed
        
        //Rende visibile il pannello uscita articoli
        closeAllExcept(jPanelExitArticle);
    }//GEN-LAST:event_jButtonUscitaArticoliActionPerformed

    //Salva tutte le informazioni dell'articolo quando viene premuto aggiungi altri articoli o fine
    private void jButtonAddItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemsActionPerformed

        saveInformationEntry();
        
        //controllare correttezza info
        
        //refresh del pannello

       
    }//GEN-LAST:event_jButtonAddItemsActionPerformed

    public void saveInformationEntry(){
        
        //salvataggio delle info dell'articolo in entrata
        String categoryArticle = jComboBoxCategoryArticle.getSelectedItem().toString();
        System.out.println("Categoria articolo: " + categoryArticle);
        
        //salvataggio del tipo di articolo
        String typeArticle = jComboBoxTypeArticle.getSelectedItem().toString();
        System.out.println("Tipo di articolo: " + typeArticle);
        
        //salvataggio della quantità di articoli
        String quantity = jTextFieldQuantity.getText();
         System.out.println("quantità: " + quantity);
         
         //salvataggio del giorno
        String day = jTextFieldDay.getText();
        System.out.print("giorno: " + day);
         
        //salvataggio del mese
        String month = jTextFieldMonth.getText();
        System.out.print(" " + month);
         
        //salvataggio dell'anno
        String year = jTextFieldYear.getText();
        System.out.println(" " + year);
        
        //salvataggio posizione x
        String positionX = jTextFieldPositionXEntry.getText();
        System.out.print("posizione: " + positionX);
        
        //salvataggio posizione y
        String positionY = jTextFieldPositionYEntry.getText();
        System.out.println(" " + positionY);     
        
                
        //salvataggio del prezzo
        String cost = jTextFieldCost.getText();
        System.out.println("Prezzo: " + cost);
    }
    
    
    //rende visibile un pannello
    public void closeAllExcept(JPanel p){
        jPanelMenu.setVisible(false);
        jPanelExitArticle.setVisible(false);
        jPanelEntryArticle.setVisible(false);
        jPanelMoveArticle.setVisible(false);
        p.setVisible(true);
    }
    
    private void jComboBoxTypeArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeArticleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeArticleActionPerformed

    private void jButtonEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEndActionPerformed
        saveInformationEntry();
        
        //controllare correttezza info
        
        //apre il pannello menu
        closeAllExcept(jPanelMenu);
    }//GEN-LAST:event_jButtonEndActionPerformed

    private void jTextFieldQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantityActionPerformed

    private void jTextFieldCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostActionPerformed

    private void jTextFieldForwarderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldForwarderNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldForwarderNameActionPerformed

    private void jComboBoxCategoryArticleExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryArticleExitActionPerformed
        switch(jComboBoxCategoryArticleExit.getSelectedItem().toString()) {
            case "BASEBALL":
                jComboBoxTypeArticleExit.removeAllItems();
                jComboBoxTypeArticleExit.addItem("bon");
                break;
           
        }
    }//GEN-LAST:event_jComboBoxCategoryArticleExitActionPerformed

    private void jTextFieldQuantityExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantityExitActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldQuantityExitActionPerformed

    private void jComboBoxTypeArticleExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeArticleExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeArticleExitActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed

        saveInformationExit();
        
        //FARE CONTROLLO INFORMAZIONI
        
        
        
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jTextFieldShopDestinationNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldShopDestinationNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldShopDestinationNameActionPerformed

    private void jButtonBackExitArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackExitArticleActionPerformed
        
        //pulsante indietro: torna alla schermata principale del magazzino
        closeAllExcept(jPanelMenu);
    }//GEN-LAST:event_jButtonBackExitArticleActionPerformed

    private void jButtonBackEntryArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackEntryArticleActionPerformed
        
        //pulsante indietro: torna alla schermata principale del magazzino
        closeAllExcept(jPanelMenu);
    }//GEN-LAST:event_jButtonBackEntryArticleActionPerformed

    private void jButtonSpostamentoArticoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpostamentoArticoliActionPerformed
        
        //Rende visibile il pannello sposta articoli
        closeAllExcept(jPanelMoveArticle);
    }//GEN-LAST:event_jButtonSpostamentoArticoliActionPerformed

    private void jButtonBackMoveArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackMoveArticleActionPerformed
        
        //apre il pannello menu
        closeAllExcept(jPanelMenu);
    }//GEN-LAST:event_jButtonBackMoveArticleActionPerformed

    private void jTextFieldRipianoScaffaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRipianoScaffaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRipianoScaffaleActionPerformed

    private void jTextFieldPositionXEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPositionXEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPositionXEntryActionPerformed

    private void jComboBoxCategoryArticleExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryArticleExit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoryArticleExit1ActionPerformed

    private void jTextFieldQuantityMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantityMoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantityMoveActionPerformed

    private void jComboBoxTypeArticleExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeArticleExit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeArticleExit1ActionPerformed

    private void jTextFieldNumeroScaffaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroScaffaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroScaffaleActionPerformed

    private void jTextFieldFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFilaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //quando viene premuto il pulsante fine, salva la posizione di dove spostare gli articoli e la quantità
        saveInformationMove();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //salvataggio delle info degli articoli in uscita
    public void saveInformationExit(){
        
        //salvataggio del nome dello spedizioniere
        String forwarderName = jTextFieldForwarderName.getText();
         System.out.println("Nome spedizioniere: " + forwarderName);
         
         //salvataggio del nome del negozio di destinaione
        String shopDestinationName = jTextFieldShopDestinationName.getText();
        System.out.println("Negozio di destinazione: " + shopDestinationName);
        
        //salvataggio della categoria di articolo in uscita
        String categoryArticleExit = jComboBoxCategoryArticleExit.getSelectedItem().toString();
        System.out.println("Categoria articolo: " + categoryArticleExit);
        
        //salvataggio del tipo di articolo
        String typeArticleExit = jComboBoxTypeArticleExit.getSelectedItem().toString();
        System.out.println("Tipo di articolo: " + typeArticleExit);
        
        //salvataggio della quantità
        String quantityExit = jTextFieldQuantityExit.getText();
        System.out.println("quantità: " + quantityExit);
        
        
    }
    
    //salvataggio delle info degli articoli spostati
    public void saveInformationMove(){
        
        //salvataggio della fila
        String filaScaffale = jTextFieldFila.getText();
         System.out.println("Fila: " + filaScaffale);
         
         //salvataggio del numero dello scaffale
        String numeroScaffale = jTextFieldNumeroScaffale.getText();
        System.out.println("Numero dello scaffale: " + numeroScaffale);
        
        //salvataggio del ripiano dello scaffale
        String ripianoScaffale = jTextFieldRipianoScaffale.getText();
        System.out.println("Ripiano: " + ripianoScaffale);
        
        //salvataggio della quantità degli articoli da spostare
        String quantity = jTextFieldQuantityMove.getText();
        System.out.println("quantità: " + quantity);
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddItems;
    private javax.swing.JButton jButtonBackEntryArticle;
    private javax.swing.JButton jButtonBackExitArticle;
    private javax.swing.JButton jButtonBackMoveArticle;
    private javax.swing.JButton jButtonEnd;
    private javax.swing.JButton jButtonEntrataArticoli;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonSpostamentoArticoli;
    private javax.swing.JButton jButtonUscitaArticoli;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<objects.Sport> jComboBoxCategoryArticle;
    private javax.swing.JComboBox<objects.Sport> jComboBoxCategoryArticleExit;
    private javax.swing.JComboBox<objects.Sport> jComboBoxCategoryArticleExit1;
    private javax.swing.JComboBox<String> jComboBoxCost;
    private javax.swing.JComboBox<String> jComboBoxCost1;
    private javax.swing.JComboBox<String> jComboBoxTypeArticle;
    private javax.swing.JComboBox<String> jComboBoxTypeArticleExit;
    private javax.swing.JComboBox<String> jComboBoxTypeArticleExit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCost;
    private javax.swing.JLabel jLabelCost1;
    private javax.swing.JLabel jLabelInfoCode;
    private javax.swing.JPanel jPanelEntryArticle;
    private javax.swing.JPanel jPanelExitArticle;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelMoveArticle;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextFieldCost;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldFila;
    private javax.swing.JTextField jTextFieldForwarderName;
    private javax.swing.JTextField jTextFieldMonth;
    private javax.swing.JTextField jTextFieldNumeroScaffale;
    private javax.swing.JTextField jTextFieldPositionXEntry;
    private javax.swing.JTextField jTextFieldPositionYEntry;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldQuantityExit;
    private javax.swing.JTextField jTextFieldQuantityMove;
    private javax.swing.JTextField jTextFieldRipianoScaffale;
    private javax.swing.JTextField jTextFieldShopDestinationName;
    private javax.swing.JTextField jTextFieldYear;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


}

